version: "3.8"

services:
    account:
        image: accountms:0.0.1-SNAPSHOT
        mem_limit: 700mb
        ports:
            - "8083:8083"
        networks:
            - abc-networks
          
    cust:
        image: custms:0.0.1-SNAPSHOT
        mem_limit: 700mb
        ports:
            - "8082:8082"
        networks:
            - abc-networks
networks:
     abc-networks:


